### ISSUE TITLE
iOS version - AppDelegate.m: RCTBundleURLProvider.h not found

### ISSUE THREAD

**Issue by fireproof** [happybai/ghost-go-app#1]
It seems  you may need to re-link your native dependencies in react-native.

http://stackoverflow.com/questions/40368211/rctbundleurlprovider-h-file-not-found-appdelegate-m

**Comment by happybai** [comment]
@fireproof Need run `npm install` to install dependencies in the console. Then run `react-native run-ios` to start app.
BTW...This project is almost a blank project.
